name: 'Terraform Azure Provisioning'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
   
    defaults:
        run:
            shell: bash
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print working directory
      run: pwd

    - name: List files
      run: ls -la

    - name: Print GITHUB_WORKSPACE
      run: echo $GITHUB_WORKSPACE

    - name: Read value from terraform.tfvars
      id: read_tfvars
      run: |
          chmod +x /home/runner/work/terraform1/terraform1/.github/workflows/read_tfvars.sh
          value=$(/home/runner/work/terraform1/terraform1/.github/workflows/read_tfvars.sh)
          echo "Value from terraform.tfvars: $value"
          echo "::set-output name=value::$value"
       
    - name: Use the value
      run: echo "Using the value:${{ steps.read_tfvars.outputs.value }}"

    - name: Print working directory
      run: pwd

    - name: List files
      run: ls -la

    - name: Print GITHUB_WORKSPACE
      run: echo $GITHUB_WORKSPACE
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Generate backend configuration
      run: |
       cat > /home/runner/work/terraform1/terraform1/terraform/backend.tf <<EOF
       terraform {
         backend "azurerm" {
            resource_group_name = "${{ secrets.AZURE_RESOURCE_GROUP }}"
            storage_account_name = "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"
            container_name = "${{ secrets.AZURE_CONTAINER_NAME }}"
            key = "${{ secrets.AZURE_AZURE_KEY }}.tfstate"
         } 
       } 
       EOF
          
    - name: List files in terraform directory
      run: ls -la /home/runner/work/terraform1/terraform1/.github/workflows
          
    - name: Terraform Init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: terraform init
      working-directory: /home/runner/work/terraform1/terraform1/terraform

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: /home/runner/work/terraform1/terraform1/terraform

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
      working-directory: /home/runner/work/terraform1/terraform1/terraform
